[package]
name = "rust-hdl-eval"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
rust-hdl = { version = "0.46.0", features = ["fpga"] }
rust-hdl-bsp-ice40-boards = { path = "../rust-hdl-bsp-ice40-boards" }
rand = {version = "0.9.2"}
