[package]
name = "rhdl-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
rhdl = {git = "https://github.com/samitbasu/rhdl"}
rhdl-fpga = {git = "https://github.com/samitbasu/rhdl", package = "rhdl-fpga"}
rhdl-bsp-ice-stick = {path = "rhdl-bsp-ice-stick"}
