[package]
name = "rhdl-bsp-ice-stick"
version = "0.1.0"
edition = "2024"

[dependencies]
rhdl = {git = "https://github.com/samitbasu/rhdl"}
rhdl-bsp = {git = "https://github.com/samitbasu/rhdl", package = "rhdl-bsp"}
